TRAIN:
  ENABLE: True
  DATASET: phakirms
  BATCH_SIZE: 24
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
TEST:
  ENABLE: True
  DATASET: phakirms
  BATCH_SIZE: 24
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 120
  MULTI_SAMPLING_RATE: [25,200,400,800]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  JUST_CENTER: False
  FIXED_RESIZE: True
  ONLINE: True
ENDOVIS_DATASET:
  DETECTION_SCORE_THRESH: 0.0
  TRAIN_USE_COLOR_AUGMENTATION: True
  INCLUDE_GT: False
  USE_PREDS: True
  TEST_LISTS: inference.csv
  TEST_PREDICT_BOX_JSON: annotations.json
MVIT:
  ZERO_DECAY_POS_CLS: False
  LOGIT_JOIN_TYPE: mlp
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPOUT_RATE: 0.0
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  DEPTH: 16
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_KVQ_KERNEL: [3, 3, 3]
  SEP_POS_EMBED: True
  CLS_EMBED_ON: True
  FREEZE_PATCH: False
REGIONS:
  ENABLE: False
  ALIGNED: True
  ROI_XFORM_RESOLUTION: 3
AUG:
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0125
  CLIP_GRAD_L2NORM: 1.0
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-4
  MAX_EPOCH: 30
  WARMUP_EPOCHS: 5.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR:  0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  ARCH: MMViT
  MODEL_NAME: MMViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TASKS:
  TASKS:  ["phases"]
  NUM_CLASSES: [7]
  LOSS_FUNC: ["cross_entropy"]
  HEAD_ACT:  ["softmax"]
  LOSS_WEIGHTS:  [1.6411019141231247,0.19090963801041133,1.0,
                  0.2502662616859295,1.9176363911137977,0.9840248158200853,
                  2.174635818337618] 
  METRICS: ["f1"]  
DATA_LOADER:
  NUM_WORKERS: 5
  PIN_MEMORY: True
FEATURES:
  ENABLE: False
MVIT_FEATS:
  ENABLE: True
  PATH: './outputs/stuff_P/features'
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: .