TRAIN:
  ENABLE: False
  DATASET: Phakir_transformer
  BATCH_SIZE: 24
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
TEST:
  ENABLE: True
  DATASET: Phakir_transformer
  BATCH_SIZE: 24
DATA:
  NUM_FRAMES: 22
  SAMPLING_RATE: 120
  MULTI_SAMPLING_RATE: [30, 60, 120, 240]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  JUST_CENTER: False
ENDOVIS_DATASET:
  DETECTION_SCORE_THRESH: 0.75
  TRAIN_USE_COLOR_AUGMENTATION: True
  INCLUDE_GT: True
  USE_PREDS: False
  TEST_LISTS: inference.csv
  TEST_PREDICT_BOX_JSON: annotations.json
  TEST_GT_BOX_JSON: annotations.json
REGIONS:
  ENABLE: False
  ALIGNED: True
  ROI_XFORM_RESOLUTION: 3
AUG:
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
SOLVER:
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.00001
  CLIP_GRAD_L2NORM: 1.0
  LR_POLICY: cosine
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-4
  MAX_EPOCH: 5
  WARMUP_EPOCHS: 0.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  ZERO_WD_1D_PARAM: True
  WARMUP_START_LR:  0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  ARCH: VideoTransformerPerFrame
  MODEL_NAME: VideoTransformerPerFrame
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.0
TASKS:
  TASKS:  ["phases"]
  NUM_CLASSES: [7]
  LOSS_FUNC: ["cross_entropy"]
  HEAD_ACT:  ["softmax"]
  LOSS_WEIGHTS:  [1.0] 
  METRICS: ["f1"]  
DATA_LOADER:
  NUM_WORKERS: 5
  PIN_MEMORY: True
FEATURES:
  ENABLE: False
TEMPORAL_MODULE:
  SAMPLING_RATE: 4
  CHUNKS: False
  NUM_FRAMES: 22
  FEATURE_PATH_VAL: "./outputs/stuff_P/features"
  FEATURE_PATH_TRAIN: "./outputs/stuff_P/features"
  STEPFORMER_D_MODEL: 256
  STEPFORMER_CAT_DIM: 768
  STEPFORMER_INPUT_DIM: 3072
  STEPFORMER_NUM_LAYERS: 4
  STEPFORMER_NUM_HEADS: 4
  ONLINE_INFERENCE: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: .